### PR TITLE
Hero section

### PR DESCRIPTION
**Pull request by Deivis151**

### CODE REVIEW

**Review by Labenas — CHANGES_REQUESTED** [review]
* Font family of original design been used poppins. It could be foun on goole fonts. As far as I notice it been used on all project. So should be placed in reset.css as main font for project
* Image looks strech to sides.
* Paragraph color should be similar to grey 
 * Responsive design missing
* probably I would remove container class from header section because right now its pushing hero section too much down.
* I think hero section do have background light grey or something similar 
* CSS of Hero section probably should be used in other file except Main.css because I think we only import other css files into main.css and keep it only with import css data. You could create Hero.css import it to main.css and style everything inside hero.css
* CSS:
.flex {
    display: flex;
    justify-content: space-between;
}

.row-center {
    flex-direction: row;
    align-items: center;
}
Flex default value is flex-direction row. So instead of seperate lines and Div you could use something like:
justify-content is used to align items on X-Axis
align-items is used to align items on Y-Axis
.flex{
    display: flex;
    justify-content: space-between;  
    align-items: center;
}
* Also I would try to avoid putting styling on items which is used in all project and use by other developer such as H1, H2,H3 .... P and so on.


                                    BUT GOOD START 👍  KEEP IT ROLLING! 👍

**Review by Saulius20 — APPROVED** [review]

**Review by Generasu — APPROVED** [review]

**Review by Generasu — APPROVED** [review]
Need this fixed html version so everyone can start working normaly, we can fix the hero section later.

**Review by belauzas — CHANGES_REQUESTED** [review]
Atstatome kitų sekcijų struktūras į pradinę versiją

**Review by belauzas — APPROVED** [review]
LGTM 🚀

**Pull request merged**
